const INIT_ACTOR_ADDRESS = "f01";
const INIT_ACTOR_INSTALL_METHOD = 3;
const INIT_ACTOR_CREATE_METHOD = 2;

module.exports = {
  INIT_ACTOR_ADDRESS,
  INIT_ACTOR_INSTALL_METHOD,
  INIT_ACTOR_CREATE_METHOD,
};
